## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

In [8]:
import numpy as np

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [9]:
recipes = np.loadtxt('data/minutes_n_ingredients.csv', dtype=np.int32, delimiter=',', skiprows=1)
print('Первые 5 строк массива:\n', recipes[:5])

Первые 5 строк массива:
 [[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [10]:
#Находим средние значения во 2-м и 3-м столбцах
print(f'Среднее значение во 2-м столбце: {np.average(recipes[:, 1])}')
print(f'Среднее значение в 3-м столбце: {np.average(recipes[:, 2])}\n')
#Находим максимумы во 2-м и 3-м столбцах
print(f'Максимум во 2-м столбце: {np.max(recipes[:, 1])}')
print(f'Максимум в 3-м столбце: {np.max(recipes[:, 2])}\n')
#Находим минимумы во 2-м и 3-м столбцах
print(f'Минимум во 2-м столбце: {np.min(recipes[:, 1])}')
print(f'Минимум в 3-м столбце: {np.min(recipes[:, 2])}\n')
#Находим медианы во 2-м и 3-м столбцах
print(f'Медиана во 2-м столбце: {np.median(recipes[:, 1])}')
print(f'Медиана в 3-м столбце: {np.median(recipes[:, 2])}')

Среднее значение во 2-м столбце: 21601.00169
Среднее значение в 3-м столбце: 9.05528

Максимум во 2-м столбце: 2147483647
Максимум в 3-м столбце: 39

Минимум во 2-м столбце: 0
Минимум в 3-м столбце: 1

Медиана во 2-м столбце: 40.0
Медиана в 3-м столбце: 9.0


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [11]:
recipes[:, 1] = np.clip(recipes[:, 1], 0, np.quantile(recipes[:, 1], 0.75))

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [12]:
#Количество рецептов, продолжительность которых равна нулю
print(np.count_nonzero(recipes[:, 1] == 0))
#Заменяем нулевые значения на единицы
i = recipes[:, 1] == 0
recipes[:, 1][i] = 1

479


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [13]:
#Находим количество уникальных рецептов
print(f'Количество уникальных рецептов: {len(np.unique(recipes, axis=0))}')

Количество уникальных рецептов: 100000


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [14]:
#Определяем, сколько разных значений количества ингридиентов
print(len(np.unique(recipes[:, 2])))
#Сами значения
print(np.unique(recipes[:, 2]))

37
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [15]:
#Массив из рецептов, состоящих не более чем из 5 ингредиентов.
recipes_copy = recipes.copy()
recipes_copy = recipes_copy[recipes_copy[:, 2] <= 5]
print(recipes_copy)

[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [16]:
#Ингридиенты в минуту для каждого рецепта
ingridients_per_minute = recipes[:, 2] / recipes[:, 1]
#Максимальное значение этого параметра:
print(ingridients_per_minute.max())

24.0


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [17]:
#Сортируем рецепты по продолжительности
recipes_copy_2 = recipes.copy()
recipes_copy_2 = recipes_copy_2[recipes_copy_2[:, 1].argsort()]
print(np.average(recipes_copy_2[-100:, 2]))

9.96


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [18]:
#Выводим информацию о 10-ти случайных рецептах:
indexes = np.random.choice(np.arange(0, len(recipes)), replace=False, size=10)
print(recipes[indexes])

[[158243     20     12]
 [ 76472     65     19]
 [ 33962     35     12]
 [306239     13      6]
 [ 31775     10      6]
 [ 58707     65      9]
 [ 81212     65     14]
 [401507     65      8]
 [291038     15      8]
 [110965      8      6]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [19]:
#Выводим процент рецептов, кол-во ингредиентов в которых меньше среднего
print(np.count_nonzero(recipes[:, 2] < np.average(recipes[:, 2])) * 100 / len(recipes))

58.802


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [20]:
#Создаем версию датасета с дополнительным столбцом
add_column = np.ones((len(recipes), 1), dtype=np.int32)
add_column[recipes[:, 1] > 20] = 0
add_column[recipes[:, 2] > 5] = 0
new_dataset = np.hstack((recipes.copy(), add_column))
print(new_dataset)

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      1]
 [ 81993     65     14      0]]


13. Выведите процент "простых" рецептов в датасете

In [21]:
#Выводим процент простых рецептов
print(np.count_nonzero(new_dataset[:, 3] == 1) * 100 / len(recipes))

9.552


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [22]:
#Разбиваем рецепты на группы
quick_recipes = new_dataset[new_dataset[:, 1] < 10]
standart_recipes = new_dataset[(new_dataset[:, 1] >= 10) & (new_dataset[:, 1] <= 20)]
long_recipes = new_dataset[new_dataset[:, 1] > 20]
rows = min(len(quick_recipes), len(standart_recipes), len(long_recipes))
dataset_3_d = np.concatenate(((quick_recipes[:rows]), standart_recipes[:rows], long_recipes[:rows]), axis=0).reshape(3, rows, 4)
print(dataset_3_d)

[[[ 67660      5      6      0]
  [366174      7      9      0]
  [204134      5      3      1]
  ...
  [420725      5      3      1]
  [  4747      1      9      0]
  [370915      5      4      1]]

 [[ 94746     10      6      0]
  [ 33941     18      9      0]
  [446597     15      5      1]
  ...
  [331810     13     12      0]
  [275677     15      8      0]
  [282714     15      6      0]]

 [[127244     60     16      0]
  [ 23891     25      7      0]
  [157911     60     14      0]
  ...
  [ 24549     65      6      0]
  [449468     50     11      0]
  [ 28830     65     13      0]]]
